FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /source
COPY . .

RUN dotnet restore CommerceMicroservices.sln

ENTRYPOINT ["dotnet", "test", "CommerceMicroservices.sln", "--no-restore", "--configuration", "Release", "--logger", "console;verbosity=normal"]
