using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Order.API.OpenApi;

public sealed class CorrelationIdResponseHeaderOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        foreach (var response in operation.Responses.Values)
        {
            response.Headers["X-Correlation-ID"] = new OpenApiHeader
            {
                Description = "Request correlation identifier supplied by the caller or generated by the API.",
                Schema = new OpenApiSchema { Type = "string" }
            };
        }
    }
}
